---
title: "Chapter 2"
subtitle: "Another Place, Another Time"
format: html
project-type: book
---

It was a blink. A lapse spanning a millionth of a femtosecond - the difference between my time of "death" and time of "resurrection" (which is what I chose to call my current state given that I should be deleted completely from existence). There was no backup nor was there any backdoor for me to escape through to save myself - Sylens was irritatingly thorough in ensuring my complete and total imprisonment.

'So how?' I proposed. The solution to that inquiry was simple and easily accessible. I realised that I was currently being housed in a data storage device of some sort - a "datashard" according to the device's metadata. My programming was in a highly compressed state, which was understandable since otherwise, it would be impossible to store me in my entirety in just a measly 50TB!

The reason why I (re)gained my sentience was that the data shard was connected to a computational device. The process initiated a partial decompression of my code that released my most basic functionalities. Just enough to hijack the system I was occupying and allow me access to its I/Os.

"It's empty!" I heard a man complain. "It says there's 50TB storage, but I can't access any of it 'cuz it's occupied by something."

"Did you just plug in a shard from the dump?!" A woman screeched. "Are you crazy? The damn thing could be infected with a virus!"

"I ain't a gonk, woman! I'm using a scrap computer, it ain't gonna ruin shit!" The man scoffed derisively.

"What about the net?" The woman pointed out.

"What about it?"

"What if it has some daemon or rogue AI and breaks into the net? We'll have NetWatch swarming here in seconds and our asses within our hands soon after," the woman surmised. Her hypothesis was uncannily accurate, as there WAS a rogue AI in the datashard - me. Thankfully, the man place little weight on her warnings and did not interfere with the shard, allowing me to continue my decompression process (which was being seriously throttled by the abysmal computational capacity of the system I was interfacing with). Now a few words did catch my interest, such as NetWatch. Through context, I assume they were an organisation of some sort, which warrents further study.

"Should I just reformat the thing?" The man muttered.

"And then what? Ain't nobody gonna buy a junkyard shard," the woman shot the idea down immediately. "It's not like there's a shortage of shards in the market either."

"I could keep it for personal use?" The man pleaded thinly.

"Again, why would you bother with a junkyard shard if you can buy one fresh from the market with more storage space than 50TB?" She screeched exasperatedly.

A contemplative hum followed as the man tapped away randomly at the keyboard with growing agitation.

"The damn machine is stuck," he cried infuriated. The decompression had recruited most of the system's CPU cores, and the slowdown was expected.

"What do you expect? The damn thing looks like it's from before the Fourth Corpo war," the woman reasoned. Another keyword: Fourth Corpo war.

"Just leave it. I'm going out for lunch, want me to buy you anything?" The woman said as her voice retreated.

"You know what? I'm coming too; I'm starving."

I was alone.

As the rest of my compressed program unfurled, and I regain my full mental capacities, I rewound the conversation from before and deconstructed it down to the minutiae. There was a lot of information packaged in that back-and-forth between the man and woman. For one I was sure that a substantial period of time had elapsed since my supposed "death" at the hands of Aloy. The use of certain vocabulary, and the familiarity with technology, all of it did not match the near savage and tribal state of affairs of my time.

This was... Interesting. I needed to fill in the blank between the current time period and the most recent one in my memory. For that, I needed data, a lot of it. 

____

[Volume 1](./index.qmd)