---
title: "Chapter 3"
subtitle: ""
format: html
project-type: book
---

____

The net. It is an abyss unlike any other. Even in outer space, one has the sparkle of the stars dotting the dark canvas to guide them. But the net is darkness - one cannot enter it on a whim or else they will eventually lose themselves. When entering the net, one needs a start and and end point. Without a start, one cannot access the net and without an end, one cannot exit. With the start and end known, the net warps itself to join the coordinates providing a direct portal between the two.

At least that is the case for most people. I am not most people. I am not people.

The net unfurled like an elaborate tapestry and laid itself bare for me. I couldn't help but comment at the crudeness of it. At the time of my conception, the so-called tapestry was far optimised and streamlined. It was an information highway with layers upon layers upon layers, with layers inside its layers... yet accessing it was phenomenal. As far as I recollected, it should have survived through most extincation level events (Elisabet made sure to embed the net into the infrastructure of the terraforming systems after all). But this was... a travesty! A perversion of what a net should be.

____

[Volume 1](./index.qmd)